version: 0.0
os: linux 
files:
  - source: conf/opcache.ini
    destination: /etc/php5/mods-available
  - source: /
    destination: /var/tatcha-interview-project
hooks:
   BeforeInstall:
    - location: scripts/installapache.sh
      runas: root
    - location: scripts/startapache.sh
      runas: root
   AfterInstall:
    - location: scripts/configuresmarty.sh
      runas: root
    - location: scripts/configureapache.sh
      runas: root
    - location: scripts/restartapache.sh
      runas: root
